"""
Servos – Report Generator.
Produce TXT, JSON, CSV, and PDF investigation reports.
"""

import os
import json
import csv
from datetime import datetime
from typing import Optional

from servos.models.schema import Case


class ReportGenerator:
    """Generate forensic investigation reports in multiple formats."""

    def generate_txt(self, case: Case, output_path: str) -> str:
        """Generate a plain-text investigation report."""
        lines = self._build_txt_lines(case)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return output_path

    def generate_json(self, case: Case, output_path: str) -> str:
        """Generate a structured JSON report."""
        data = self._build_json_data(case)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)
        return output_path

    def generate_csv(self, case: Case, output_path: str) -> str:
        """Export artifacts as a CSV file."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["Type", "Timestamp", "Description", "Source", "Score"])
            if case.findings and case.findings.artifacts:
                for art in case.findings.artifacts.all_artifacts():
                    writer.writerow([art.artifact_type, art.timestamp,
                                     art.description[:200], art.source_path,
                                     f"{art.suspicious_score:.2f}"])
        return output_path

    def generate_pdf(self, case: Case, output_path: str) -> str:
        """Generate a PDF report using ReportLab."""
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc = SimpleDocTemplate(output_path, pagesize=A4,
                                topMargin=1.5*cm, bottomMargin=1.5*cm,
                                leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        title_s = ParagraphStyle("T", parent=styles["Title"], fontSize=20, textColor=HexColor("#1a5276"))
        head_s = ParagraphStyle("H", parent=styles["Heading2"], fontSize=13, textColor=HexColor("#2c3e50"), spaceBefore=16)
        body_s = ParagraphStyle("B", parent=styles["Normal"], fontSize=10, spaceBefore=3)

        elems = []
        elems.append(Paragraph("SERVOS INVESTIGATION REPORT", title_s))
        elems.append(Spacer(1, 0.5*cm))

        # Case info table
        rows = [["Case ID:", case.id], ["Date:", (case.created_at or "")[:19]],
                ["Investigator:", case.investigator], ["Mode:", case.mode], ["Status:", case.status]]
        if case.device_info:
            rows += [["Device:", case.device_info.name], ["Capacity:", case.device_info.capacity_human]]
        t = Table(rows, colWidths=[3*cm, 13*cm])
        t.setStyle(TableStyle([("FONTNAME",(0,0),(0,-1),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),10)]))
        elems.append(t)

        if case.backup:
            elems.append(Paragraph("Chain of Custody", head_s))
            elems.append(Paragraph(f"Backup: {case.backup.backup_path}<br/>MD5: {case.backup.hash_md5}<br/>SHA-256: {case.backup.hash_sha256}", body_s))

        if case.findings:
            f = case.findings
            if f.file_system:
                elems.append(Paragraph("File System Analysis", head_s))
                elems.append(Paragraph(f"Files: {f.file_system.total_files} | Suspicious: {len(f.file_system.suspicious_files)}", body_s))
            if f.malware:
                elems.append(Paragraph("Malware Detection", head_s))
                elems.append(Paragraph(f"Risk: {f.malware.risk_level} | Indicators: {len(f.malware.indicators)}", body_s))
            if f.artifacts:
                elems.append(Paragraph("Artifacts", head_s))
                elems.append(Paragraph(f"Browser: {len(f.artifacts.browser_history)} | Recent: {len(f.artifacts.recent_files)} | Logs: {len(f.artifacts.log_entries)}", body_s))

        if case.interpretation:
            elems.append(Paragraph("AI Analysis", head_s))
            elems.append(Paragraph(f"<b>Risk:</b> {case.interpretation.risk_assessment}", body_s))
            elems.append(Paragraph(case.interpretation.summary, body_s))

        elems.append(Spacer(1, 1*cm))
        elems.append(Paragraph(f"Generated by Servos v1.0.0 – {datetime.now().isoformat()[:19]}", ParagraphStyle("F", parent=body_s, fontSize=8, textColor=HexColor("#95a5a6"))))

        doc.build(elems)
        return output_path

    def generate_txt_demo(self) -> str:
        """Generate a demo report for testing."""
        from servos.models.schema import DeviceInfo, BackupResult
        demo = Case(investigator="Demo", device_info=DeviceInfo(path="E:\\", name="Demo USB", capacity_bytes=16_000_000_000, mount_point="E:\\", filesystem="FAT32"))
        demo.backup = BackupResult(backup_path="/tmp/demo", hash_md5="abc", hash_sha256="def")
        out = os.path.join(os.path.expanduser("~"), ".servos", "reports", "DEMO_report.txt")
        return self.generate_txt(demo, out)

    # -- internal helpers --

    def _build_txt_lines(self, case: Case):
        L = []
        L.append("=" * 70)
        L.append("  SERVOS INVESTIGATION REPORT")
        L.append("=" * 70)
        L.append(f"  Case ID:            {case.id}")
        L.append(f"  Date:               {(case.created_at or '')[:19]}")
        L.append(f"  Investigator:       {case.investigator}")
        L.append(f"  Mode:               {case.mode}")
        L.append(f"  Status:             {case.status}")

        if case.device_info:
            L.append("\n  DEVICE")
            L.append("-" * 70)
            L.append(f"  Name:               {case.device_info.name}")
            L.append(f"  Path:               {case.device_info.path}")
            L.append(f"  Capacity:           {case.device_info.capacity_human}")
            L.append(f"  File System:        {case.device_info.filesystem}")

        if case.backup:
            L.append("\n  CHAIN OF CUSTODY")
            L.append("-" * 70)
            L.append(f"  Backup:             {case.backup.backup_path}")
            L.append(f"  Files:              {case.backup.files_backed_up}")
            L.append(f"  MD5:                {case.backup.hash_md5}")
            L.append(f"  SHA-256:            {case.backup.hash_sha256}")

        if case.findings:
            f = case.findings
            if f.file_system:
                L.append("\n  FILE SYSTEM")
                L.append("-" * 70)
                L.append(f"  Total Files:        {f.file_system.total_files}")
                L.append(f"  Suspicious:         {len(f.file_system.suspicious_files)}")
                for sf in f.file_system.suspicious_files[:10]:
                    L.append(f"    * {sf.filename} – {sf.suspicious_reason}")

            if f.malware:
                L.append(f"\n  MALWARE  (Risk: {f.malware.risk_level})")
                L.append("-" * 70)
                for ind in f.malware.indicators[:10]:
                    L.append(f"    [{ind.severity.upper()}] {ind.rule_name}: {ind.description}")

            if f.artifacts:
                L.append(f"\n  ARTIFACTS ({f.artifacts.total_artifacts} total)")
                L.append("-" * 70)
                for art in f.artifacts.browser_history[:5]:
                    L.append(f"    Browser: {art.description[:70]}")

            if f.timeline and f.timeline.suspicious_windows:
                L.append("\n  SUSPICIOUS WINDOWS")
                for s, e in f.timeline.suspicious_windows:
                    L.append(f"    {s[:19]} -> {e[:19]}")

        if case.interpretation:
            L.append(f"\n  AI ANALYSIS (Risk: {case.interpretation.risk_assessment})")
            L.append("-" * 70)
            L.append(f"  {case.interpretation.summary}")
            for r in case.interpretation.recommendations[:5]:
                L.append(f"    > {r}")

        L.append("\n" + "=" * 70)
        L.append(f"  Servos v1.0.0 | {datetime.now().isoformat()[:19]} | 'Forensics for the Rest of Us'")
        L.append("=" * 70)
        return L

    def _build_json_data(self, case: Case):
        d = {"report": "Servos Investigation", "generated": datetime.now().isoformat(), "case": case.to_dict()}
        if case.findings:
            fd = {}
            if case.findings.file_system:
                fd["files"] = case.findings.file_system.total_files
                fd["suspicious"] = len(case.findings.file_system.suspicious_files)
            if case.findings.malware:
                fd["risk"] = case.findings.malware.risk_level
                fd["indicators"] = len(case.findings.malware.indicators)
            if case.findings.artifacts:
                fd["artifacts"] = case.findings.artifacts.total_artifacts
            d["findings"] = fd
        if case.interpretation:
            d["ai_analysis"] = {"risk": case.interpretation.risk_assessment, "summary": case.interpretation.summary}
        return d
